x = "asd"
try:
    y = 5 + x
except:
    print("'int' and 'str'")
    """
    eğer try kodlarında hata varsa except içindeki kodlar çalışacağından hata gözükmez
    """